# https://vercel.com/guides/how-can-i-use-github-actions-with-vercel
name: Deploy Vercel Preview

on: push

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  deploy:
    name: Deploy

    # See https://runs-on.com/runners/linux/
    runs-on:
      [
        runs-on,
        runner=8cpu-linux-x64,
        disk=large,
        "run-id=${{ github.run_id }}",
      ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: |
            backend/requirements/default.txt
            backend/requirements/dev.txt
            backend/requirements/model_server.txt
      - run: |
          python -m pip install --upgrade pip
          pip install --retries 5 --timeout 30 -r backend/requirements/default.txt
          pip install --retries 5 --timeout 30 -r backend/requirements/dev.txt
          pip install --retries 5 --timeout 30 -r backend/requirements/model_server.txt

      - name: Generate OpenAPI schema
        working-directory: ./backend
        env:
          PYTHONPATH: "."
        run: |
          python scripts/onyx_openapi_schema.py --filename generated/openapi.json

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install node dependencies
        working-directory: ./web
        run: npm ci

      - name: Generate OpenAPI TypeScript Client (orval)
        working-directory: ./web
        run: |
          npx orval --config orval.config.js

      # NOTE: Vercel pulls the working directory (web) from the project dashboard settings          
      - name: Install vercel globally
        run: |
          npm install --global vercel
          
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
        
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
        
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
